### ISSUE TITLE
Problem setting presets in PropertyWidget

### ISSUE THREAD

**Issue by wl-stepp** [pymmcore-plus/pymmcore-widgets#245]
* pymmcore-widgets version: 0.1.dev190+g3f1e2ea
* Python version: 3.11.4
* Operating System: Windows 10

### Description

Trying to modify a Preset in the GroupPresetTableWidget. A value that comes out of our Prime BSI seems to overflow for setting a slider.

### What I Did

```
C:\iSIM\iSIM\gui\.venv\Lib\site-packages\vispy\visuals\_scalable_textures.py:295: RuntimeWarning: overflow encountered in scalar subtract
  clim_min = (clim_min - range_min) / (range_max - range_min)
WARNING: Traceback (most recent call last):
  File "C:\iSIM\pymmcore-widgets\src\pymmcore_widgets\_group_preset_widget\_group_preset_table_widget.py", line 331, in _edit_group
    self._edit_group_wdg = EditGroupWidget(group, parent=self)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\iSIM\pymmcore-widgets\src\pymmcore_widgets\_group_preset_widget\_edit_group_widget.py", line 35, in __init__
    self._create_gui()
  File "C:\iSIM\pymmcore-widgets\src\pymmcore_widgets\_group_preset_widget\_edit_group_widget.py", line 53, in _create_gui
    table = self._create_table_wdg()
            ^^^^^^^^^^^^^^^^^^^^^^^^
    self._prop_table = DevicePropertyTable(enable_property_widgets=False)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\iSIM\pymmcore-widgets\src\pymmcore_widgets\_device_property_table.py", line 98, in __init__
    self._rebuild_table()
  File "C:\iSIM\pymmcore-widgets\src\pymmcore_widgets\_device_property_table.py", line 149, in _rebuild_table
    wdg = PropertyWidget(
          ^^^^^^^^^^^^^^^
  File "C:\iSIM\pymmcore-widgets\src\pymmcore_widgets\_property_widget.py", line 325, in __init__
    self._value_widget = _creat_prop_widget(self._mmc, device_label, prop_name)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\iSIM\pymmcore-widgets\src\pymmcore_widgets\_property_widget.py", line 254, in _creat_prop_widget
    wdg.setMaximum(wdg.type_cast(mmcore.getPropertyUpperLimit(dev, prop)))
  File "C:\iSIM\iSIM\gui\.venv\Lib\site-packages\superqt\sliders\_labeled.py", line 68, in setMaximum
    self._slider.setMaximum(maximum)
OverflowError: argument 1 overflowed: value must be in the range -2147483648 to 2147483647
```

**Comment by tlambert03** [comment]
Yeah, that's a known issue, see https://github.com/pymmcore-plus/pymmcore-widgets/issues/223

We do try to at least catch the errors though since https://github.com/pymmcore-plus/pymmcore-widgets/pull/224. But perhaps we need an additional try somewhere
